### ISSUE TITLE
bufio.Scanner: token too long

### ISSUE THREAD

**Issue by edgar1992** [openfaas/of-watchdog#105]
when the forked process has too long log, it will cause 'bufio.Scanner: token too long'
https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

**Comment by alexellis** [comment]
What use-case do you have, that is writing to stdio with a huge output? The of-watchdog is designed primarily for use with the HTTP mode which should only write occasional, and very brief debug messages.

Can you help us understand what you're trying to achieve here?

**Comment by alexellis** [comment]
Closing as duplicate of https://github.com/openfaas/of-watchdog/issues/100 - however, I'd still like to hear from you on the above @edgar1992

**Comment by hdaginawala-infoblox** [comment]
bufio.Scanner: token too long 

what would cause the above message? 
For perspective, This is from a logging host which is created, which ideally receives logs from one source and sends it to another

**Comment by alexellis** [comment]
Hi @hdaginawala-infoblox 

It would seem that you've commented on an old issue

Please raise your own issue in this repository and fill out the whole issue template.

You should also see the "log_buffer_size" note in the README of this repository.

Alex
