### ISSUE TITLE
Duplicated copy line in Dockerfile

### ISSUE THREAD

**Issue by itsksaurabh** [openfaas/of-watchdog#108]
## Current Behaviour

There are some areas of improvement in the current [Dockerfile](https://github.com/openfaas/of-watchdog/blob/master/Dockerfile):

**1.** Repeats similar build steps ( layers ). It can be seen [here](https://github.com/openfaas/of-watchdog/blob/ec85b31ffb89697063fb002ddacec2097a47b3d1/Dockerfile#L13).

```
COPY metrics             metrics
COPY metrics             metrics
```

**2.** Build Args are there but not used anywhere inside the Dockerfile which can be seen [here](https://github.com/openfaas/of-watchdog/blob/ec85b31ffb89697063fb002ddacec2097a47b3d1/Dockerfile#L3).

## Possible Solution

Possible solutions:

**1.** Remove extra similar layers as it is not required.

**2.**  Use the build args inside the Dockerfile for dynamic builds. For example : 

```
ARG CGO_ENABLED=0
........
............
# Stripping via -ldflags "-s -w" 
RUN CGO_ENABLED=$CGO_ENABLED GOOS=linux go build -a -ldflags "-s -w" -installsuffix cgo -o of-watchdog . \
.......
..............
```
## Steps to Reproduce (for bugs)

none

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Docker version 19.03.8, build afacb8b
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
/set title: Duplicated copy line in Dockerfile

**Comment by alexellis** [comment]
Happy for you to send a PR to remove the duplicated line. the ARGS can be changed to ENV if they are not used.

**Comment by itsksaurabh** [comment]
@alexellis Thanks for the review. I am removing that duplicated copy of the line from the Dockerfile with my PR. 
Before changing ARGS to ENV, I would like to discuss it in the slack channel. :)
