### ISSUE TITLE
Support issue

### ISSUE THREAD

**Issue by junneyang** [openfaas/of-watchdog#111]
1、of-watchdog，max_inflight = 1
![image](https://user-images.githubusercontent.com/6802322/92985443-1a0d7880-f4e5-11ea-9394-53fa520e7a81.png)

2、template：python3-http（https://github.com/openfaas-incubator/python-flask-template/tree/master/template/python3-http）

3、the log show that multiple request are handling concurrently：
![image](https://user-images.githubusercontent.com/6802322/92985483-75d80180-f4e5-11ea-9dbe-7ec307d317de.png)

**Comment by alexellis** [comment]
Share how you are invoking?

Also this doesn't necessarily mean it's not working. It's just showing a thread number, by default there are 4.

**Comment by junneyang** [comment]
@alexellis  thanks, it's about the container oomkiller and restart
