### ISSUE TITLE
Documentation - missing mode parameter

### ISSUE THREAD

**Issue by tmiklas** [openfaas/of-watchdog#118]
Small improvement

Documentation section is missing the `mode` parameter in the table of configuration options. 
Luckily examples show at least one invocation of environment vars like `mode=http` etc. to switch operating mode from default `streaming`  to other variants.

**Comment by alexellis** [comment]
Is this a duplicate of #117 @tmiklas ?

**Comment by tmiklas** [comment]
yes, no idea how/why it was created
