### ISSUE TITLE
When prefix_logs="false" is set, % signs logged by the function are interpreted as fmt.Printf verbs

### ISSUE THREAD

**Issue by jcollie** [openfaas/of-watchdog#132]
If you set the environment variable prefix_logs to false, % signs are interpreted by of-watchdog as fmt.Printf verbs.

## Expected Behaviour
% signs should not be interpreted

## Current Behaviour
If your function logs "%s", of-watchdog substitutes "%!s(MISSING)"

## Possible Solution

Don't use fmt.Printf() to log data from the function.

## Steps to Reproduce (for bugs)
1. Create a function that has ENV prefix_logs="false"
2. Deploy that function
3. Log "%s" from your function.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.13

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 1.23.5

* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS 7

* Link to your project or a code example to reproduce issue:

**Comment by LucasRoesler** [comment]
I think this makes sense and should be a relatively small change to https://github.com/openfaas/of-watchdog/blob/a0289419078824f0a070860f84a6b383eb4f2169/executor/logging.go

@jcollie  would you be willing to open a Pull Request?

**Comment by jcollie** [comment]
> Does this also affect the [classic watchdog](https://github.com/openfaas/classic-watchdog/)?

Not from what I saw, but I've never personally used the classic watchdog and I only spent a few minutes looking at the code.
