### ISSUE TITLE
Use of-watchdog for Docker template running a C/C++ function

### ISSUE THREAD

**Issue by salminsu** [openfaas/of-watchdog#135]
Hi,
I have used the Docker template to run a C/C++ function with the classic watchdog. I, however, need the of-watchdog model in 'http' mode. Since there is no Docker template for that, I tried to understand the of-watchdog http-runner code and [golang-http-template](https://github.com/openfaas/golang-http-template). As the C/C++ function to run in the docker, I incorporated a C/C++ http-server in the function. While the http server works standalone, the of-watchdog in 'http' mode + Docker running C/C++ function does not work. It shows 'Server returned unexpected status code: 500 - ' error. How can I debug the issue further? Is there anything else needed to enable Docker function for of-watchdog? I am new to OpenFaaS, so any help will be appreciated. I've attached the Dockerfile and C/C++ function code.
 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 20.10.12
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Using Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20
* Link to your project or a code example to reproduce issue:
[function.zip](https://github.com/openfaas/of-watchdog/files/8655938/function.zip)

**Comment by salminsu** [comment]
@alexellis: I was talking in the context of this issue that I raised yesterday. Please let me know if you need more context.

**Comment by taorepoara** [comment]
Hi,

Why do you need the http mode for a very simple function like this one ?

The of your configuration is that the `fprocess` env var in the Dockerfile has `xargs` before your process. Removing it works fine.

Best regards,

Thomas

**Comment by alexellis** [comment]
For free technical support, attend our weekly Office Hours call in the docs under Community 

docs.openfaas.com
