### ISSUE TITLE
Support request (need more info)

### ISSUE THREAD

**Issue by luke-powers** [openfaas/of-watchdog#151]
`faas-cli publish` does not work any longer, giving an error that the of-watchdog image is missing. It appears that all OpenFAAS images are missing: [https://hub.docker.com/u/openfaas](https://hub.docker.com/u/openfaas)

This just an outage or did I miss something related to [this](https://blog.alexellis.io/docker-is-deleting-open-source-images/)?

Thanks for any info.

**Comment by alexellis** [comment]
Hi Luke,

Please fill out the whole issue template if you'd like support.

https://github.com/openfaas/of-watchdog/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by alexellis** [comment]
/set title: Support request (need more info)

**Comment by alexellis** [comment]
@luke-powers you opened this issue, do you need help or can it be closed?

**Comment by Xtrah** [comment]
@luke-powers you need to update your code to pull from [GitHub Container Registry](https://github.com/openfaas/of-watchdog/pkgs/container/of-watchdog) instead of Docker Hub.

https://www.openfaas.com/blog/how-does-docker-hub-affect-openfaas/

**Comment by alexellis** [comment]
Thanks for trying to help @Xtrah 

I was trying to find out what @luke-powers was doing before giving an answer. This way, we may never know and may not have the insights to help other users :disappointed:

**Comment by Xtrah** [comment]
Sorry! You may delete my comment in that case @alexellis 🙏
