### ISSUE TITLE
Websockets and HTTP mode

### ISSUE THREAD

**Issue by rosko** [openfaas/of-watchdog#20]
Is it possible to use `of-watchdog` in HTTP mode to support websockets?

## Your Environment
* Docker 18.03.1
* Docker Swarm (locally) and Kubernetes (on Azure, in the future)
* Windows and MacOS locally, Linux on the server.

**Comment by alexellis** [comment]
Not right now since we'd have no way of giving QoS i.e. timeouts etc. 

What is the usecase for a websocket to a function? How would you see timeouts working with this?

Alex

**Comment by rosko** [comment]
We can consider a websocket server as a set of event handlers: `connection`, `disconnect`, `message`. In this case, it seems possible to be implemented using functions. And timeouts can work with that concept similarly as with regular serverless functions. Does it make sense?

**Comment by alexellis** [comment]
Websockets are inherently stateful with long running connections. How do you implement a timeout for an operation? 

Maybe you could start with giving us a usecase in as much detail as you're comfortable with and we can try to explore the idea from there?

**Comment by rosko** [comment]
@alexellis WDUT?

**Comment by rosko** [comment]
@rvanzon not yet :)

**Comment by lucasvfventura** [comment]
@alexellis My team is using GraphQL and we use subscriptions to push events to the UI that were triggered by other users. Subscriptions use Websocket behind the scene. This is the only point keeping us to move to a completely serverless solution.

Serverless.com with AWS supports it with the "new" API Gateway websockets api, but it isn't available yet in my GraphQL framework integration with the serverless framework.

**Comment by matti** [comment]
my usecase: run https://github.com/ws-doom

**Comment by alexellis** [comment]
I'm going to close this issue as it's already been answered.

We may consider websocket support in the future, however we've had no requests from commercial users for this as of yet. Ideally, we'd be looking for one of them to sponsor the work and maintenance of the feature. It would also break any timeouts and limits that people expect from FaaS platforms like OpenFaaS and Cloud Run.

**Comment by colearendt** [comment]
Just want to add some context here. In addition to streaming applications, there are a handful of app development frameworks in the data science ecosystem (Shiny, Streamlit, etc.) that depend heavily on websockets. The other place I have seen applications are in TTYs (terminal-emulators) and other heavily responsive / stateful applications.

With regard to how to set timeouts, I have seen many transparent proxies use something like ["proxy read timeout"](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) or ["proxy write timeout."](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout). In traefik (written in Go), [`idleTimeout`](https://doc.traefik.io/traefik/v1.7/configuration/commons/#timeouts) seems to be the operative target. 

In any case, websockets or other `keep-alive` connections seem to be handled independently of other types of requests.

The behavior that I experienced with `fwatchdog` not handling websockets definitely surprised me and took a while to debug - it just holds the socket open and doesn't return the data until the backend connection dies or `fwatchdog`'s shutdown sequence is initiated. `tcpdump` on the container (which showed my function returning data from 8082->8080, and data never getting returned from 8080) was what finally led me to this thread.

(FWIW I'm not sure if this is the right GitHub repo or if I am using the "classic" watchdog, but this seemed like the newer target for feature discussions!)
