### ISSUE TITLE
Make mode=serializing be fully backwards compatible with the original watchdog

### ISSUE THREAD

**Issue by thomasjpfan** [openfaas/of-watchdog#32]
For `of-watchdog` to take the place of the original watchdog, it should be fully backwards compatible with the original watchdog.

## Expected Behavior
Support environmental variables `cgi_headers`, `marshal_request`, and `combine_output` with their corresponding feature.

## Current Behavior
The above features are not fully supported.

## Possible Solution
Migrate over the tests and code from the original watchdog.

## Context
Maintaining two versions of watchdog doubles the amount of work one needs to do. Once `of-watchdog` in serializing mode becomes backwards compatible, it can replace the original `watchdog` while the other modes can get worked on.

**Comment by sargun** [comment]
@alexellis is this and #10 the only remaining items to be able to supplant the old watchdog?

**Comment by alexellis** [comment]
Hi I am not clear what the question is. There are two supported watchdogs at present. 

For the forking mode we have the classic watchdog and for HTTP mode we are using this watchdog. Both watchdogs are used by the end user community in templates. 

https://docs.openfaas.com/architecture/watchdog/
